[package]
name = "stonetr03/admincube"
version = "3.0.0-pre"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
Fusion = "elttob/fusion@0.2.0"
Signal = "sleitnick/signal@1.1.0"
Topbar = "1foreverhd/topbarplus@3.3.1"